name: CI-CD

on:
  push:
    branches: ["main"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3.5.3
    
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v2.2.0
      username: ${{secrets.DOCKERHUB_USER}}
      password: ${{secrets.DOCKERHUB_PWD}}
    
    
    - name: Contrução da imagem Docker
      uses: docker/build-push-action@v4.1.1
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
            davicarneiro/kube-news-aula:v1
            davicarneiro/kube-news-aula:latest
    
